@startuml
' Définition des entités
entity "USER" {
  +id_user : INT
  name : TEXT
  email : TEXT
  password : TEXT
  date_created : DATE
  status : TEXT
  --
  +id_role : INT
}

entity "RECIPE" {
  +id_recipe : INT
  title : TEXT
  description : TEXT
  anecdote : TEXT
  ingredients : TEXT
  instructions : TEXT
  source : TEXT
  date_added : DATE
}

entity "CATEGORY" {
  +id_category : INT
  name : TEXT
}

entity "COMMENT" {
  +id_comment : INT
  content : TEXT
  date_comment : DATE
  --
  +id_user : INT
  +id_recipe : INT
}

entity "SCORE" {
  score : INT
  --
  +id_user : INT
  +id_recipe : INT
}

entity "ROLE" {
  +id_role : INT
  role : TEXT
}

' Relations entre les entités
USER }|--|| ROLE : "HAVE"
USER }|--|| RECIPE : "CREATE"
USER }|--|| COMMENT : "LEAVE"
USER ||--|| SCORE : "GIVE"
RECIPE ||--|{ CATEGORY : "ASSOCIATE"
SCORE }o--|{ RECIPE : "RECEIVE"
COMMENT }o--|{ RECIPE : "ACCEPT"
@enduml