@startuml
left to right direction

actor "Guest" as G #lightcyan
actor "User" as U #lightgreen
actor "Admin" as A #lightpink

rectangle "System" {

  usecase "View all Recipes" as UC1 #lightcyan
  usecase "Search Recipe by Title or Movie/TV Show" as UC2 #lightcyan
  usecase "View Recipe Details" as UC3 #lightcyan
  usecase "Create Account and Authenticate" as UC4 #lightcyan
  usecase "Modify User Profile" as UC5 #lightgreen
  usecase "Add a Recipe" as UC6 #lightcyan
  usecase "Leave a Comment on a Recipe" as UC7 #lightgreen
  usecase "Rate a Recipe" as UC8 #lightgreen
  usecase "Manage Users (Moderate Accounts, Delete Accounts)" as UC9 #lightpink
  usecase "Validate or Delete User-Submitted Recipes" as UC10 #lightpink
  usecase "Moderate User Comments" as UC11 #lightpink
  usecase "Delete Recipe" as UC12 #lightpink
  usecase "View Recipe Score and Comments" as UC13 #lightcyan
}

' Guest Access (light gray)
G -down-> UC1
G -down-> UC2
G -down-> UC3
G -down-> UC4
G -down-> UC6
G -down-> UC13

' User Access (light blue)
U -down-> UC5
U -down-> UC7
U -down-> UC8

' Admin Access (light green)
A -down-> UC9
A -down-> UC10
A -down-> UC11
A -down-> UC12
@enduml