Table "ACCEPT" {
  "code_Recipe"  VARCHAR(42) [NOT NULL]
  "code_Comment" VARCHAR(42) [NOT NULL]
  Indexes {
    ("code_Recipe", "code_Comment") [pk]
  }
}

Table "CATEGORY" {
  "code_Category" VARCHAR(42) [pk, NOT NULL]
  "name"          VARCHAR(42)
  "code_Recipe"   VARCHAR(42) [NOT NULL]
}

Table "COMMENT" {
  "code_Comment" VARCHAR(42) [pk, NOT NULL]
  "content"      VARCHAR(42)
  "date_comment" VARCHAR(42)
}

Table "RECEIVE" {
  "code_Recipe" VARCHAR(42) [NOT NULL]
  "score"       VARCHAR(42) [NOT NULL]
  Indexes {
    ("code_Recipe", "score") [pk]
  }
}

Table "RECIPE" {
  "code_Recipe"  VARCHAR(42) [pk, NOT NULL]
  "title"        VARCHAR(42)
  "description"  VARCHAR(42)
  "anecdote"     VARCHAR(42)
  "ingredients"  VARCHAR(42)
  "instructions" VARCHAR(42)
  "source"       VARCHAR(42)
  "date_added"   VARCHAR(42)
}

Table "ROLE" {
  "code_Role" VARCHAR(42) [pk, NOT NULL]
  "role"      VARCHAR(42)
}

Table "SCORE" {
  "score"     VARCHAR(42) [pk, NOT NULL]
  "code_User" VARCHAR(42) [NOT NULL]
  Indexes {
    "code_User" [unique]
  }
}

Table "USER" {
  "code_User"    VARCHAR(42) [pk, NOT NULL]
  "name"         VARCHAR(42)
  "email"        VARCHAR(42)
  "password"     VARCHAR(42)
  "date_created" VARCHAR(42)
  "status"       VARCHAR(42)
  "code_Comment" VARCHAR(42) [NOT NULL]
  "code_Role"    VARCHAR(42) [NOT NULL]
  "code_Recipe"  VARCHAR(42) [NOT NULL]
}

Ref:"ACCEPT"."code_Recipe" > "RECIPE"."code_Recipe"
Ref:"ACCEPT"."code_Comment" > "COMMENT"."code_Comment"
Ref:"CATEGORY"."code_Recipe" > "RECIPE"."code_Recipe"
Ref:"RECEIVE"."code_Recipe" > "RECIPE"."code_Recipe"
Ref:"RECEIVE"."score" > "SCORE"."score"
Ref:"SCORE"."code_User" > "USER"."code_User"
Ref:"USER"."code_Comment" > "COMMENT"."code_Comment"
Ref:"USER"."code_Role" > "ROLE"."code_Role"
Ref:"USER"."code_Recipe" > "RECIPE"."code_Recipe"
