-- Generated by Mocodo 4.2.11

CREATE TABLE ACCEPT (
  PRIMARY KEY (code_Recipe, code_Comment),
  code_Recipe  VARCHAR(42) NOT NULL,
  code_Comment VARCHAR(42) NOT NULL
);

CREATE TABLE CATEGORY (
  PRIMARY KEY (code_Category),
  code_Category VARCHAR(42) NOT NULL,
  name          VARCHAR(42),
  code_Recipe   VARCHAR(42) NOT NULL
);

CREATE TABLE COMMENT (
  PRIMARY KEY (code_Comment),
  code_Comment VARCHAR(42) NOT NULL,
  content      VARCHAR(42),
  date_comment VARCHAR(42)
);

CREATE TABLE RECEIVE (
  PRIMARY KEY (code_Recipe, score),
  code_Recipe VARCHAR(42) NOT NULL,
  score       VARCHAR(42) NOT NULL
);

CREATE TABLE RECIPE (
  PRIMARY KEY (code_Recipe),
  code_Recipe  VARCHAR(42) NOT NULL,
  title        VARCHAR(42),
  description  VARCHAR(42),
  anecdote     VARCHAR(42),
  ingredients  VARCHAR(42),
  instructions VARCHAR(42),
  source       VARCHAR(42),
  date_added   VARCHAR(42)
);

CREATE TABLE ROLE (
  PRIMARY KEY (code_Role),
  code_Role VARCHAR(42) NOT NULL,
  role      VARCHAR(42)
);

CREATE TABLE SCORE (
  PRIMARY KEY (score),
  score     VARCHAR(42) NOT NULL,
  code_User VARCHAR(42) NOT NULL,
  UNIQUE (code_User)
);

CREATE TABLE USER (
  PRIMARY KEY (code_User),
  code_User    VARCHAR(42) NOT NULL,
  name         VARCHAR(42),
  email        VARCHAR(42),
  password     VARCHAR(42),
  date_created VARCHAR(42),
  status       VARCHAR(42),
  code_Comment VARCHAR(42) NOT NULL,
  code_Role    VARCHAR(42) NOT NULL,
  code_Recipe  VARCHAR(42) NOT NULL
);

ALTER TABLE ACCEPT ADD FOREIGN KEY (code_Comment) REFERENCES COMMENT (code_Comment);
ALTER TABLE ACCEPT ADD FOREIGN KEY (code_Recipe) REFERENCES RECIPE (code_Recipe);

ALTER TABLE CATEGORY ADD FOREIGN KEY (code_Recipe) REFERENCES RECIPE (code_Recipe);

ALTER TABLE RECEIVE ADD FOREIGN KEY (score) REFERENCES SCORE (score);
ALTER TABLE RECEIVE ADD FOREIGN KEY (code_Recipe) REFERENCES RECIPE (code_Recipe);

ALTER TABLE SCORE ADD FOREIGN KEY (code_User) REFERENCES USER (code_User);

ALTER TABLE USER ADD FOREIGN KEY (code_Recipe) REFERENCES RECIPE (code_Recipe);
ALTER TABLE USER ADD FOREIGN KEY (code_Role) REFERENCES ROLE (code_Role);
ALTER TABLE USER ADD FOREIGN KEY (code_Comment) REFERENCES COMMENT (code_Comment);
