@startuml
left to right direction

actor "User" as U
actor "Admin" as A

rectangle "System" {
  
  usecase "View Recipes by Category" as UC1
  usecase "Search Recipe by Title or Movie/TV Show" as UC2
  usecase "View Recipe Details" as UC3
  usecase "Create Account and Authenticate" as UC4
  usecase "Modify User Profile" as UC5
  usecase "Add a Recipe" as UC6
  usecase "Leave a Comment on a Recipe" as UC7
  usecase "Rate a Recipe" as UC8
  usecase "View Recipes Sorted by score or Date Added" as UC10
  usecase "View Recipes by Specific Ingredients" as UC11
  
  usecase "Manage Users (Moderate Accounts, Delete Accounts)" as UC12
  usecase "Validate or Delete User-Submitted Recipes" as UC13
  usecase "Organize Recipes into Categories" as UC14
  usecase "Moderate User Comments" as UC15
}

U -down-> UC1
U -down-> UC2
U -down-> UC3
U -down-> UC4
U -down-> UC5
U -down-> UC6
U -down-> UC7
U -down-> UC8
U -down-> UC10
U -down-> UC11

A -down-> UC12
A -down-> UC13
A -down-> UC14
A -down-> UC15
@enduml